name: CI

on: push

jobs:
  commit-check:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      name: Checkout latest master

    - name: Set up Docker Compose
      run: docker-compose up -d --build

    - name: Install Composer dependencies
      run: docker exec deploy-server-php-fpm composer install --no-interaction
    
    - name: Run PHPStan
      run: docker exec deploy-server-php-fpm vendor/phpstan/phpstan/phpstan

  deploy:
    runs-on: ubuntu-latest
    needs: commit-check
    if: github.ref == 'refs/heads/master' # Runs only on push to master

    steps:
      - uses: actions/checkout@v2
        name: Checkout latest master

      - name: Deploy to server
        run: echo "Deploying to server..." 
