name: CI

on: push

jobs:
  commit-check:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      name: Checkout latest master

    - name: Set up Docker Compose
      run: docker-compose up -d --build

    - name: Install Composer dependencies
      run: docker exec deploy-server-php-fpm composer install --no-interaction
    
    - name: Run PHPStan
      run: docker exec deploy-server-php-fpm vendor/phpstan/phpstan/phpstan

    - name: Run PHP-CS-Fixer
      run: docker exec deploy-server-php-fpm vendor/friendsofphp/php-cs-fixer/php-cs-fixer fix --dry-run --allow-risky=yes --verbose --show-progress dots

  deploy:
    runs-on: ubuntu-latest
    needs: commit-check
    if: github.ref == 'refs/heads/master' # Runs only on push to master

    steps:
      - uses: actions/checkout@v2
        name: Checkout latest master
    
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'

      - name: Deploy to server
        run: echo "Deploying to server..."

      - name: Get deploy token
        id: deploy_token
        run: echo "::set-output name=token::$(php examples/get_token.php)"

      - name: Echo Token
        run: echo "The token is ${{ steps.deploy_token.outputs.token }}"
