name: CI

on:
  push:
    branches: [ master ]

jobs:
  prepare-container:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      name: Checkout latest master

    - name: Set up Docker Compose
      run: |
        docker-compose up -d --build

    - name: Install Composer dependencies
      run: docker-compose exec -T deploy-server-php-fpm composer install --no-interaction

  phpstan-check:
    runs-on: ubuntu-latest
    needs: prepare-container
    steps:
      - name: Run PHPStan
        run: docker-compose exec -T deploy-server-php-fpm phpstan
